name: Sync LeetCode
on:
  workflow_dispatch: # Allows you to run it manually anytime
  schedule:
    - cron: '30 17 * * *' # Runs every night at 11:00 PM IST (17:30 UTC)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Submissions
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: 'my-solutions' # This keeps new ones in a specific folder
          verbose: true
